import {FactoryView} from './factory-view.js';
const $=id=>document.getElementById(id);
const labels={baseline:'현재 운영',robot:'로봇 자동화',training:'검사 교육',combined:'자동화 + 교육'};
let experiment=null,current='combined',viewer=null,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,time=90,last=0;
try{viewer=new FactoryView($('scene'));}catch(e){$('scene-error').hidden=false;$('scene-error').textContent='3D 화면을 열 수 없습니다. WebGL을 지원하는 브라우저에서 다시 열어 주세요. 비교 결과는 아래에서 확인할 수 있습니다.';console.error(e);}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||data.message||'요청 처리에 실패했습니다.');return data;}
const fmt=(n,d=1)=>Number.isFinite(Number(n))?Number(n).toFixed(d):'—';
function setText(id,s){$(id).textContent=s;}
function metric(s,k){return Number(s.metrics?.[k]??0);}
function updatePlan(p){const i=p.interpretation||{};setText('plan-mode',p.mode==='llm'?'로컬 Qwen 실행 완료':'규칙 기준선');$('interpretation').replaceChildren();for(const [k,v]of [['주문 배수',`${fmt(i.demand_multiplier??1.0,2)}배`],['로봇 대안',i.allow_robot===false?'제외':'허용'],['교육 대안',i.allow_training===false?'제외':'허용'],['대안 선택 시간',`${fmt(p.latency_ms??0,0)} ms`]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;$('interpretation').append(dt,dd);}setText('selected-plan',(p.selected_ids||[]).map(id=>labels[id]||id).join(' · '));$('rationale').replaceChildren();for(const text of p.rationale||[]){const li=document.createElement('li');li.textContent=typeof text==='string'?text:JSON.stringify(text);$('rationale').append(li);}setText('raw-plan',JSON.stringify({model:p.model,mode:p.mode,selected_focus_id:p.selected_focus_id,raw_output:p.raw_output,source_ids:p.source_ids,warnings:p.warnings,plan_id:p.plan_id},null,2));}
function setScenario(id){current=id;const s=experiment?.scenarios.find(s=>s.id===id);if(!s)return;$('scenario').value=id;setText('scenario-name',s.name||labels[id]);setText('metric-completed',`${fmt(metric(s,'completed'))}개`);setText('metric-wait',`${fmt(metric(s,'mean_wait_min'))}분`);setText('metric-skill',`${fmt(metric(s,'skill_coverage_pct'),0)}%`);setText('metric-training',`${fmt(metric(s,'training_hours'),0)}시간`);viewer?.setScenario(s);time=90;}
function renderResults(){const all=experiment.scenarios,max=Math.max(...all.map(s=>metric(s,'completed')),1);$('comparison-bars').replaceChildren();$('comparison-table').replaceChildren();for(const s of all){const m=s.metrics,c=document.createElement('article');c.className='bar-card'+(s.id===experiment.recommendation?.scenario_id?' recommended':'');const h=document.createElement('h3');h.textContent=s.name||labels[s.id];const value=document.createElement('p');value.className='value';value.textContent=fmt(m.completed)+'개';const note=document.createElement('small');note.textContent='8시간 완료 수량 · 10회 평균';const track=document.createElement('div');track.className='bar-track';const bar=document.createElement('div');bar.className='bar-fill';bar.style.width=100*Number(m.completed)/max+'%';track.append(bar);const range=document.createElement('p');range.className='bar-range';const seedMetric=s.summary?.completed;range.textContent=seedMetric?`실행 범위 ${fmt(seedMetric.min,0)}–${fmt(seedMetric.max,0)}개`:'고정 난수 조건 10개';c.append(h,value,note,track,range);$('comparison-bars').append(c);const tr=document.createElement('tr');for(const v of [s.name||labels[s.id],fmt(m.completed)+'개',fmt(m.mean_wait_min)+'분',fmt(m.wip_end)+'개',fmt(m.skill_coverage_pct,0)+'%',fmt(m.training_hours,0)+'시간']){const td=document.createElement('td');td.textContent=v;tr.append(td);}$('comparison-table').append(tr);}const r=experiment.recommendation||{},best=all.find(s=>s.id===r.scenario_id)||all[0],hr=experiment.hr;setText('insight',`${best.name}의 완료 수량은 평균 ${fmt(best.metrics.completed)}개입니다. 교육 부담과 미확인 도입 비용을 함께 검토해야 합니다.`);setText('hr-readout',hr?`가상 역량 원본 ${hr.total_workers}행을 검증했습니다. 검사 가능 인원 ${hr.qualified_before}명에서 ${hr.qualified_after}명으로 확보하는 대안의 역량 공백은 ${hr.skill_gap_to_candidate}명이며, 가정한 교육 투입은 ${hr.total_training_hours}시간입니다. 검증 결과 오류 ${hr.input_quality?.error_count??0}건과 원본 해시를 비교 기록에 함께 저장했습니다.`:'전체 작업자 수를 유지하면서 검사 역량을 가진 인원의 비율과 교육 부담을 함께 보여줍니다.');setText('experiment-meta',`비교 ID ${experiment.experiment_id} / ${experiment.horizon_min}분 / seed ${(experiment.seeds||[]).join(', ')}`);}
function renderExperiment(e){experiment=e;updatePlan(e.plan||{});$('scenario').replaceChildren();for(const s of e.scenarios){const option=document.createElement('option');option.value=s.id;option.textContent=s.name||labels[s.id];$('scenario').append(option);}renderResults();setScenario(e.recommendation?.scenario_id||e.scenarios.at(-1).id);refreshHistory();}
async function refreshHistory(){try{const data=await api('/api/history');const items=Array.isArray(data)?data:data.items||data.history||[];$('history').replaceChildren();for(const i of items){const li=document.createElement('li'),button=document.createElement('button');button.textContent=`${i.experiment_id||i.id} · ${i.request||i.created_at||'저장된 비교'}`;button.addEventListener('click',async()=>{try{renderExperiment(await api('/api/experiment?id='+encodeURIComponent(i.experiment_id||i.id)));}catch(e){setText('request-state',e.message);}});li.append(button);$('history').append(li);}}catch(e){console.error(e);}}
$('plan').addEventListener('click',async()=>{$('plan').disabled=true;setText('request-state',$('mode').value==='llm'?'로컬 모델이 대안을 고르고 있습니다. 첫 실행은 모델 준비 시간이 필요합니다.':'규칙 기준선으로 대안을 준비합니다.');try{const p=await api('/api/plan',{request:$('request').value,mode:$('mode').value});updatePlan(p);setText('request-state','선택한 대안을 같은 주문·난수 조건에서 실행 중입니다.');const e=await api('/api/compare',{plan_id:p.plan_id});renderExperiment(e);setText('request-state',`${p.mode==='llm'?'실제 로컬 Qwen':'규칙 기준선'} 실행 · ${fmt(p.latency_ms,0)} ms · 비교 기록 저장 완료`);}catch(e){setText('request-state',e.message);}finally{$('plan').disabled=false;}});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.view));viewer?.resize();}));
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{$('request').value=b.dataset.preset==='training'?'주문량이 20% 늘었습니다. 로봇 추가 없이 검사 교육만 비교해 주세요.':'주문량이 20% 늘었습니다. 교육 없이 로봇 자동화만 비교해 주세요.';}));
$('scenario').addEventListener('change',()=>setScenario($('scenario').value));$('play').addEventListener('click',()=>{playing=!playing;setText('play',playing?'일시정지':'재생');});$('clock').addEventListener('input',()=>{time=Number($('clock').value);});$('download').addEventListener('click',()=>{if(!experiment)return;const url=URL.createObjectURL(new Blob([JSON.stringify(experiment,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`factory-${experiment.experiment_id}.json`;a.click();URL.revokeObjectURL(url);});
function animate(ms){const dt=Math.min((ms-last)/1000,.1);last=ms;if(playing&&experiment&&$('factory').classList.contains('active'))time=(time+dt*Number($('speed').value))%480;$('clock').value=time;setText('clock-label',`${Math.round(time)} / 480분`);viewer?.render(time);requestAnimationFrame(animate);}requestAnimationFrame(animate);if(!playing)setText('play','재생');
async function init(){try{const s=await api('/api/status');setText('model-status',s.model?.available?'Qwen2.5 · 로컬 CPU 준비됨':'모델 없음 · 규칙 모드 사용 가능');if(!s.model?.available)$('mode').value='rules';renderExperiment(await api('/api/demo'));}catch(e){setText('request-state',e.message);}}init();
