const $=id=>document.getElementById(id);
let fixture=null,current=null,polling=false;
const names={submitted:'접수',validated:'검수 통과',analyzing:'실제 AI 비교 중',analyzed:'공정 비교 완료',awaiting_approval:'승인 대기',decision_pending:'n8n 결정 처리 중',approved:'승인·기록 완료',rejected:'거절·기록 완료',blocked:'입력 오류 차단',failed:'실행 실패'};
const scenario={baseline:'기준 공정',robot:'AMR·로봇',training:'검사 교육',combined:'자동화 + 교육'};
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||d.message||'요청에 실패했습니다.');return d;}
function show(job){current=job;$('state').textContent=names[job.state]||job.state;$('job-title').textContent=job.request||'요청과 비교 기록';$('job-id').textContent=`요청 ID ${job.id||job.request_id}`;$('execution-id').textContent=`n8n 실행 ID ${job.n8n_execution_id||job.execution_id||'—'}`;$('flow-state').textContent=job.state==='blocked'?'잘못된 원장은 LLM 실행 전에 차단했습니다.':job.state==='rejected'?'거절 결과를 기록했으며 교육 계획을 만들지 않았습니다.':job.state==='approved'?'n8n이 결정 후 기록을 확정했습니다.':`현재 단계: ${names[job.state]||job.state}`;
 const at={submitted:0,validated:1,analyzing:2,analyzed:3,awaiting_approval:4,decision_pending:5,approved:6,rejected:5,blocked:1,failed:2}[job.state]??0;[...$('stages').children].forEach((n,i)=>{n.className=i<at?'done':i===at?'active':'';});
 const r=job.result||job.experiment||{};const exp=r.experiment||r;const rows=exp.scenarios||[];$('replay-link').href=rows.length?'/replay.html#id='+encodeURIComponent(job.id||job.request_id):'http://127.0.0.1:8771/';$('replay-link').textContent=rows.length?'이 요청의 공장 재생 ↗':'움직이는 공장 보기 ↗';$('result').hidden=!rows.length;$('empty').hidden=!!rows.length||['blocked','failed'].includes(job.state);const retry=job.state==='decision_pending'&&job.events?.some(e=>e.stage==='resume_failed')&&!job.events?.some(e=>e.stage==='resume_acknowledged');$('approval').hidden=job.state!=='awaiting_approval'&&!retry;$('approve').hidden=retry&&job.decision!=='approve';$('reject').hidden=retry&&job.decision!=='reject';$('approve').textContent=retry?'같은 승인 다시 전송':'합성 계획 승인';$('reject').textContent=retry?'같은 거절 다시 전송':'계획 거절';$('bars').replaceChildren();const max=Math.max(...rows.map(s=>s.metrics.completed),1);for(const s of rows){const card=document.createElement('article');card.className='bar'+(s.id===exp.recommendation?.scenario_id?' best':'');const h=document.createElement('h3');h.textContent=scenario[s.id]||s.name;const value=document.createElement('strong');value.textContent=Number(s.metrics.completed).toFixed(1)+'개';const track=document.createElement('div');track.className='track';const bar=document.createElement('span');bar.style.width=(100*s.metrics.completed/max)+'%';track.append(bar);const note=document.createElement('small');note.textContent='8시간 완료 / 10회 평균';card.append(h,value,track,note);$('bars').append(card);}
 const summary=job.summary||r.summary||{};const p=exp.plan||r.plan||{};$('explanation').textContent=summary.explanation||`비교한 대안 중 ${scenario[exp.recommendation?.scenario_id]||'—'}의 완료 수량이 가장 많습니다. 교육 효과와 실제 도입비는 가정·미검증입니다.`;$('model-detail').textContent=p.model?`${p.model.name} · 실제 선택 ${scenario[p.selected_focus_id]||p.selected_focus_id} · ${((p.latency_ms??exp.plan?.latency_ms??0)/1000).toFixed(2)}초 · 공정 수치는 SimPy 계산`:'계산 기록 확인 중';
 const issues=job.issues||job.validation?.issues||[];$('issues').hidden=!issues.length&&job.state!=='failed';$('issues').textContent=issues.length?issues.map(i=>`${i.code||'검수'}: ${i.reason||i.message||'입력 조건 확인 필요'}`).join('\n'):job.error||job.error_code||'실행에 실패했습니다. 기록을 확인해 주세요.';
 const training=job.training_plan;$('saved').hidden=!['approved','rejected'].includes(job.state);$('saved').textContent=job.state==='rejected'?'거절 기록 저장 완료 · 교육 계획 0건':training?`승인한 합성 교육 계획 저장 완료 · 참여 ${training.training_participants??training.participants??1}명 / ${training.total_training_hours??training.training_hours??training.hours??8}시간 · 검사 자격 확보 가정 1→2명`:'승인 기록 저장 완료 · 비교 대안에 교육이 없어 교육 계획 0건';
 $('events').replaceChildren();for(const event of job.events||[]){const li=document.createElement('li');li.textContent=[event.created_at||event.at,event.type||event.event||event.stage||event.state,event.detail||event.note].filter(Boolean).map(v=>typeof v==='string'?v:JSON.stringify(v)).join(' · ');$('events').append(li);}$('evidence').textContent=JSON.stringify({id:job.id||job.request_id,state:job.state,n8n_execution_id:job.n8n_execution_id||job.execution_id,model:p.model,selected_focus_id:p.selected_focus_id,source_sha256:exp.hr?.source_json_sha256,decision:job.decision,training_plan:training},null,2);
}
async function history(){const d=await api('/api/jobs');$('history').replaceChildren();for(const j of d.items||[]){const b=document.createElement('button');b.className='history-item';const state=document.createElement('span');state.textContent=names[j.state]||j.state;const req=document.createElement('span');req.textContent=j.request||'합성 비교 요청';const id=document.createElement('small');id.textContent=j.id||j.request_id;b.append(state,req,id);b.onclick=async()=>{show(await api('/api/job?id='+encodeURIComponent(j.id||j.request_id)));watch();};$('history').append(b);}}
async function watch(){if(polling||!current)return;polling=true;try{show(await api('/api/job?id='+encodeURIComponent(current.id||current.request_id)));await history();}catch(e){$('submit-status').textContent=e.message;}finally{polling=false;}}
$('submit').onclick=async()=>{$('submit').disabled=true;try{const records=JSON.parse($('records').value);const d=await api('/api/submit',{request:$('request').value,records,synthetic:true,idempotency_key:crypto.randomUUID()});const id=d.id||d.request_id||d.job?.id;show(d.job||await api('/api/job?id='+encodeURIComponent(id)));$('submit-status').textContent='실제 n8n 워크플로에 접수했습니다.';await history();}catch(e){$('submit-status').textContent=e.message;}finally{$('submit').disabled=false;}};
async function decide(decision){$('approve').disabled=$('reject').disabled=true;try{await api('/api/decision',{request_id:current.id||current.request_id,decision});await watch();}catch(e){$('submit-status').textContent=e.message;}finally{$('approve').disabled=$('reject').disabled=false;}}
$('approve').onclick=()=>decide('approve');$('reject').onclick=()=>decide('reject');$('valid').onclick=()=>{$('records').value=JSON.stringify(fixture.records,null,2);};$('invalid').onclick=()=>{const rows=structuredClone(fixture.records);delete rows[0].skills.inspection;$('records').value=JSON.stringify(rows,null,2);};$('refresh').onclick=()=>history().catch(e=>$('submit-status').textContent=e.message);
async function init(){try{fixture=await api('/api/fixture');$('records').value=JSON.stringify(fixture.records,null,2);await history();}catch(e){$('submit-status').textContent=e.message;}}init();setInterval(()=>{if(current&&!['approved','rejected','blocked','failed'].includes(current.state))watch();},1500);
